# Banco-Ice/dockerfiles/Dockerfile.banco-client-admin

FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@9 --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

ENV VITE_AUTH_URL=http://localhost:5210/api/v1
ENV VITE_ADMIN_URL=http://localhost:3050/BankingService/v1

EXPOSE 5174

CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5174"]
