# Banco-Ice/dockerfiles/Dockerfile.banking-service

FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.29.3 --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

ENV PORT=3050
ENV URI_MONGODB=mongodb://mongodb:27017/banking-service
ENV JWT_SECRET=\$ecretKeyForBanking-\$ervice2024177
ENV JWT_EXPIRES_IN=1h
ENV JWT_ISSUER=BankingService
ENV JWT_AUDIENCE=BankingService
ENV NODE_TLS_REJECT_UNAUTHORIZED=0

EXPOSE 3050

CMD ["sh", "-c", "chmod +x node_modules/.bin/* && pnpm run dev"]
